package primero;
// Generated 13-nov-2018 9:32:54 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private int stockactual;
	private int stockminimo;
	private int pvp;
	private Set<Ventas> ventases = new HashSet<Ventas>(0);

	public Productos() {
	}

	public Productos(int stockactual, int stockminimo, int pvp) {
		this.stockactual = stockactual;
		this.stockminimo = stockminimo;
		this.pvp = pvp;
	}

	public Productos(String descripcion, int stockactual, int stockminimo, int pvp, Set<Ventas> ventases) {
		this.descripcion = descripcion;
		this.stockactual = stockactual;
		this.stockminimo = stockminimo;
		this.pvp = pvp;
		this.ventases = ventases;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getStockactual() {
		return this.stockactual;
	}

	public void setStockactual(int stockactual) {
		this.stockactual = stockactual;
	}

	public int getStockminimo() {
		return this.stockminimo;
	}

	public void setStockminimo(int stockminimo) {
		this.stockminimo = stockminimo;
	}

	public int getPvp() {
		return this.pvp;
	}

	public void setPvp(int pvp) {
		this.pvp = pvp;
	}

	public Set<Ventas> getVentases() {
		return this.ventases;
	}

	public void setVentases(Set<Ventas> ventases) {
		this.ventases = ventases;
	}

}
