package primero;
// Generated 13-nov-2018 9:32:54 by Hibernate Tools 3.5.0.Final

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	private Integer idventa;
	private Productos productos;
	private Clientes clientes;
	private String fechaventa;
	private int cantidad;

	public Ventas() {
	}

	public Ventas(Productos productos, Clientes clientes, int cantidad) {
		this.productos = productos;
		this.clientes = clientes;
		this.cantidad = cantidad;
	}

	public Ventas(Productos productos, Clientes clientes, String fechaventa, int cantidad) {
		this.productos = productos;
		this.clientes = clientes;
		this.fechaventa = fechaventa;
		this.cantidad = cantidad;
	}

	public Integer getIdventa() {
		return this.idventa;
	}

	public void setIdventa(Integer idventa) {
		this.idventa = idventa;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(String fechaventa) {
		this.fechaventa = fechaventa;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
